DonetCoreMVCApp/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EFCoreBikeStores.Models;
using DonetCoreBikeStoresRepository.Contracts;
using System.Diagnostics;
using DonetCoreMVCApp.Models;
using Microsoft.AspNetCore.Http;

namespace DonetCoreMVCApp.Controllers
{
 public class CustomersController : Controller
 {
  private readonly IRepositoryWrapper _repoWrapper;

  public CustomersController(IRepositoryWrapper repoWrapper)
  {
   _repoWrapper = repoWrapper;
  }

  // GET: Customers
  public async Task<IActionResult> Index()
  {
   int? customerId = Request.HttpContext.Session.GetInt32("userId");
   if (customerId.HasValue && customerId.Value > 0)
   {
    return RedirectToAction("Details", new { id = customerId });
   }
   else
   {
    return View(_repoWrapper.Customers.FindAll());
   }
  }

  public async Task<IActionResult> Impersonate(int? id)
  {
   int customerId = (id.HasValue ? id.Value : -1);
   Request.HttpContext.Session.SetInt32("userId", customerId);
   return RedirectToAction("Details", new { id = id });
  }

  public async Task<IActionResult> StopImpersonate()
  {
   Request.HttpContext.Session.SetInt32("userId", -1);
   return RedirectToAction("Index");
  }


  // GET: Customers/Details/5
  public async Task<IActionResult> Details(int? id)
  {
   if (!id.HasValue)
   {
    return NotFound();
   }

   var customers =  _repoWrapper.Customers.FindByCondition(m => m.CustomerId == id)
    .Include(c => c.Orders)
    .ThenInclude(co => co.OrderItems)
    .ThenInclude(cop => cop.Product).ToList<Customers>();

   if (customers == null || customers.Count < 1 )
   {
    return NotFound();
   }
   return View(customers[0]);
  }

  [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
  public IActionResult Error()
  {
   return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
  }
 }
}

DonetCoreMVCApp/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EFCoreBikeStores.Models;
using DonetCoreBikeStoresRepository.Contracts;

namespace DonetCoreMVCApp.Controllers
{
  public class ProductsController : Controller
  {
    private readonly IRepositoryWrapper _repoWrapper;

    public ProductsController(IRepositoryWrapper repoWrapper)
    {
      _repoWrapper = repoWrapper;
    }

    // GET: Products
    public async Task<IActionResult> Index()
    {
      var products = _repoWrapper.Products.FindAll().Include(p => p.Brand).Include(p => p.Category).AsQueryable();
      return View(products);
    }

    public PartialViewResult ListingTable()
    {
      var products = _repoWrapper.Products.FindAll().Include(p => p.Brand).Include(p => p.Category).AsQueryable();
      return PartialView("_ListingTable", products);
    }

    public PartialViewResult ListingTiles(int? id)
    {
      if(id == null)
      {
        id = 1;
      }
      var products = _repoWrapper.Products.FindAll().Include(p => p.Brand).Include(p => p.Category).AsQueryable();
      return PartialView("_ListingTiles", products.Take(12 * id.Value));
    }
    //// GET: Products/Details/5
    //public async Task<IActionResult> Details(int? id)
    //{
    //    if (id == null)
    //    {
    //        return NotFound();
    //    }

    //    var products = await _context.Products
    //        .Include(p => p.Brand)
    //        .Include(p => p.Category)
    //        .FirstOrDefaultAsync(m => m.ProductId == id);
    //    if (products == null)
    //    {
    //        return NotFound();
    //    }

    //    return View(products);
    //}

    //// GET: Products/Create
    //public IActionResult Create()
    //{
    //    ViewData["BrandId"] = new SelectList(_context.Brands, "BrandId", "BrandName");
    //    ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName");
    //    return View();
    //}

    //// POST: Products/Create
    //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    //[HttpPost]
    //[ValidateAntiForgeryToken]
    //public async Task<IActionResult> Create([Bind("ProductId,ProductName,BrandId,CategoryId,ModelYear,ListPrice")] Products products)
    //{
    //    if (ModelState.IsValid)
    //    {
    //        _context.Add(products);
    //        await _context.SaveChangesAsync();
    //        return RedirectToAction(nameof(Index));
    //    }
    //    ViewData["BrandId"] = new SelectList(_context.Brands, "BrandId", "BrandName", products.BrandId);
    //    ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", products.CategoryId);
    //    return View(products);
    //}

    //// GET: Products/Edit/5
    //public async Task<IActionResult> Edit(int? id)
    //{
    //    if (id == null)
    //    {
    //        return NotFound();
    //    }

    //    var products = await _context.Products.FindAsync(id);
    //    if (products == null)
    //    {
    //        return NotFound();
    //    }
    //    ViewData["BrandId"] = new SelectList(_context.Brands, "BrandId", "BrandName", products.BrandId);
    //    ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", products.CategoryId);
    //    return View(products);
    //}

    //// POST: Products/Edit/5
    //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    //[HttpPost]
    //[ValidateAntiForgeryToken]
    //public async Task<IActionResult> Edit(int id, [Bind("ProductId,ProductName,BrandId,CategoryId,ModelYear,ListPrice")] Products products)
    //{
    //    if (id != products.ProductId)
    //    {
    //        return NotFound();
    //    }

    //    if (ModelState.IsValid)
    //    {
    //        try
    //        {
    //            _context.Update(products);
    //            await _context.SaveChangesAsync();
    //        }
    //        catch (DbUpdateConcurrencyException)
    //        {
    //            if (!ProductsExists(products.ProductId))
    //            {
    //                return NotFound();
    //            }
    //            else
    //            {
    //                throw;
    //            }
    //        }
    //        return RedirectToAction(nameof(Index));
    //    }
    //    ViewData["BrandId"] = new SelectList(_context.Brands, "BrandId", "BrandName", products.BrandId);
    //    ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", products.CategoryId);
    //    return View(products);
    //}

    //// GET: Products/Delete/5
    //public async Task<IActionResult> Delete(int? id)
    //{
    //    if (id == null)
    //    {
    //        return NotFound();
    //    }

    //    var products = await _context.Products
    //        .Include(p => p.Brand)
    //        .Include(p => p.Category)
    //        .FirstOrDefaultAsync(m => m.ProductId == id);
    //    if (products == null)
    //    {
    //        return NotFound();
    //    }

    //    return View(products);
    //}

    //// POST: Products/Delete/5
    //[HttpPost, ActionName("Delete")]
    //[ValidateAntiForgeryToken]
    //public async Task<IActionResult> DeleteConfirmed(int id)
    //{
    //    var products = await _context.Products.FindAsync(id);
    //    _context.Products.Remove(products);
    //    await _context.SaveChangesAsync();
    //    return RedirectToAction(nameof(Index));
    //}

    //private bool ProductsExists(int id)
    //{
    //    return _context.Products.Any(e => e.ProductId == id);
    //}
  }
}

DonetCoreMVCApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DonetCoreMVCApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <link href="~/lib/bootstrap-toggle/css/bootstrap-toggle.css" rel="stylesheet" />
    <link href="~/css/mvc-grid/mvc-grid.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3 navbar-fixed-top my-navbar">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DonetCoreMVCApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Bikes Listing</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container my-body-container ">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - DonetCoreMVCApp - Vikram Gopu
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/bootstrap-toggle/js/bootstrap-toggle.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/mvc-grid/mvc-grid.js"></script>
    <script>
        [].forEach.call(document.getElementsByClassName('mvc-grid'), function (element) {
            new MvcGrid(element);
        });
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>